export enum AuthorActionTypes {
  REQUEST_AUTHORS = 'REQUEST_AUTHORS',
  SET_AUTHORS = 'SET_AUTHORS',
  SET_LOADING_AUTHORS = 'SET_LOADING_AUTHORS',

  SET_AUTHOR_FILTER = 'SET_AUTHOR_FILTER',
  CLEAR_AUTHORS_LIST = 'CLEAR_AUTHORS_LIST',

  CLEAR_AUTHORS_STATE = 'CLEAR_AUTHORS_STATE',
};

export type AuthorState = {
  authors: any,
};
